- name: Install system packages
  hosts: all
  roles:
    - base_system
    - docker


# - name: Install Google Chrome
#   hosts: localhost
#   roles:
#     - google_chrome

# - name: Install PHP 8.2
#   hosts: localhost
#   roles:
#     - edw_php
#   vars:
#     - php_version: 8.2
#     - php_custom_settings:
#         - {option: "memory_limit", value: "1024M", section: "PHP"}

# - name: Install PHP 8.1
#   hosts: localhost
#   roles:
#     - edw_php
#   vars:
#     - php_version: 8.1
#     - php_custom_settings:
#         - {option: "memory_limit", value: "1024M", section: "PHP"}

# - name: Install PHP 7.4
#   hosts: localhost
#   roles:
#     - edw_php
#   vars:
#     - php_version: 7.4
#     - php_custom_settings:
#         - {option: "memory_limit", value: "1024M", section: "PHP"}
