---
system_packages:
  - build-essential
  - bzip2
  - dos2unix
  - firefox
  - gimp
  - git
  - gitk
  - htop
  - hwdata
  - inetutils-traceroute
  - magic-wormhole
  - mc
  - mkcert
  - mtools
  - net-tools
  - nmap
  - ntp
  - nvme-cli
  - openssl
  - p7zip-full
  - python3-pip
  - python3-virtualenv
  - pwgen
  - screenruler
  - siege
  - simplescreenrecorder
  - tcpdump
  - telnet
  - vim
  - vim-common
  - warpinator
  - wget
  - wkhtmltopdf
  - zip
