---
- name: Test apt file exists
  stat:
    path: "{{ google_chrome_apt_file }}"
  register: google_apt_exists
  ignore_errors: true

- name: Add Google Chrome apt key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  when: google_apt_exists

- name: Add Google Chrome repository
  copy:
    content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    dest: "{{ google_chrome_apt_file }}"
    owner: "root"
    group: "root"
    mode: "644"
  when: google_apt_exists

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    update_cache: true
